"""Added notes to tasks

Revision ID: 672d4ef03bca
Revises: c54eacb5ff79
Create Date: 2026-05-13 09:24:28.184276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672d4ef03bca'
down_revision = 'c54eacb5ff79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
