"""Added index and created_at fields to categories and tasks

Revision ID: 70c7b4e456b2
Revises: a4c132ef9468
Create Date: 2026-06-03 12:07:10.444895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c7b4e456b2'
down_revision = 'a4c132ef9468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('category', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.create_index(op.f('ix_todo_user_id'), 'todo', ['user_id'], unique=False)
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_index(op.f('ix_todo_user_id'), table_name='todo')
    op.drop_column('category', 'created_at')
    op.drop_column('todo', 'created_at')

    # ### end Alembic commands ###
