"""Added index to more colomns

Revision ID: 7a80d37f5334
Revises: 70c7b4e456b2
Create Date: 2026-06-04 09:06:45.658763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a80d37f5334'
down_revision = '70c7b4e456b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('todo_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_category_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_category_todo_id'), ['todo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_category_todo_id'))
        batch_op.drop_index(batch_op.f('ix_todo_category_category_id'))

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_created_at'))
        batch_op.drop_index(batch_op.f('ix_todo_completed'))

    # ### end Alembic commands ###
