"""Replaced individual indexes with compound indexes

Revision ID: b5fe38b4a01b
Revises: 7a80d37f5334
Create Date: 2026-06-04 09:18:59.939912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fe38b4a01b'
down_revision = '7a80d37f5334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_completed'))
        batch_op.drop_index(batch_op.f('ix_todo_created_at'))
        batch_op.drop_index(batch_op.f('ix_todo_user_id'))
        batch_op.create_index('ix_todo_user_completed_created', ['user_id', 'completed', 'created_at'], unique=False)

    with op.batch_alter_table('todo_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_category_todo_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_category_todo_id'), ['todo_id'], unique=False)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index('ix_todo_user_completed_created')
        batch_op.create_index(batch_op.f('ix_todo_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_completed'), ['completed'], unique=False)

    # ### end Alembic commands ###
