"""Redid photos

Revision ID: ee70939fad38
Revises: 81e3848d6c27
Create Date: 2026-03-06 23:22:12.026873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee70939fad38'
down_revision = '81e3848d6c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.TEXT(), nullable=True))
        batch_op.drop_column('profile_pic_url')

    # ### end Alembic commands ###
